### PR TITLE
Revert go-genproto api update that is incompatible with Kubernetes

### PR DESCRIPTION
**Pull request by TristonianJones**
Revert the go-genproto api update which is incompatible with Kubernetes builds since it brings in a denylisted dependency. The change has no effect the main CEL module, and dependent submodules which care about the update will receive it via minimum version selection.

### CODE REVIEW

**Comment by TristonianJones** [comment]
@DangerOnTheRanger FYI

**Review by jpbetz — APPROVED** [review]
LGTM

**Comment by DangerOnTheRanger** [comment]
LGTM as well.

**Comment by cici37** [comment]
Thank you!
/lgtm

**Pull request merged**
